# Generated by Django 2.1.7 on 2019-04-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Twit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=240)),
                ('liked_by', models.ManyToManyField(related_name='likes', to='people.Person')),
                ('retwited_by', models.ManyToManyField(related_name='retwits', to='people.Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twits', to='people.Person')),
            ],
        ),
        migrations.AddField(
            model_name='replies',
            name='twit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='twits.Twit'),
        ),
        migrations.AddField(
            model_name='replies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='people.Person'),
        ),
    ]
