# Generated by Django 2.1.7 on 2019-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='twit',
            name='retwited_by',
            field=models.ManyToManyField(blank=True, related_name='retwits', to='people.Person'),
        ),
    ]
