# Generated by Django 2.1.7 on 2019-06-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190518_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='followers',
        ),
        migrations.AddField(
            model_name='person',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to='people.Person'),
        ),
    ]
